//
// Created by chris on 9/8/2025.
//

#ifndef PLATFORMIO_NULI_AIRBRAKES_SOFTWARE_APOGEEPREDICTOR_H
#define PLATFORMIO_NULI_AIRBRAKES_SOFTWARE_APOGEEPREDICTOR_H


class ApogeePredictor {

};


#endif //PLATFORMIO_NULI_AIRBRAKES_SOFTWARE_APOGEEPREDICTOR_H
